# Generated by Django 5.2.4 on 2025-07-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book details'), ('can_create_book', 'Can create new books'), ('can_edit_book', 'Can edit existing books'), ('can_delete_book', 'Can delete books')]},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'permissions': [('can_add_book', 'Can add book to library'), ('can_change_book', 'Can change book in library'), ('can_delete_book', 'Can delete book from library')]},
        ),
    ]
